package com.semeruk.android_dagger2;

import android.app.Application;

import com.semeruk.android_dagger2.component.ApplicationComponent;
import com.semeruk.android_dagger2.component.DaggerApplicationComponent;
import com.semeruk.android_dagger2.module.ApplicationModule;

public class CustomApplication extends Application {

    private ApplicationComponent mApplicationComponent;

    @Override
    public void onCreate() {
        super.onCreate();

        // Generated by Dagger
        mApplicationComponent = DaggerApplicationComponent.builder()
                // List of modules that are part of this component
                .applicationModule(new ApplicationModule(this))
                .build();

        // If a Dagger 2 component does not have any constructor arguments for any of its modules,
        // then we can use .create() as a shortcut instead:
        // mAppComponent = com.codepath.dagger.components.DaggerAppComponent.create();
    }

    public ApplicationComponent getApplicationComponent() {
        return mApplicationComponent;
    }
}